export const FETCH_STREAM = 'FETCH_STREAM'
export const FETCH_STREAM_PENDING = 'FETCH_STREAM_PENDING'
export const FETCH_STREAM_FULFILLED = 'FETCH_STREAM_FULFILLED'
export const FETCH_STREAM_REJECTED = 'FETCH_STREAM_REJECTED'